export const CREATE_FILE = "CREATE_FILE";
export const DELETE_FILE = "DELETE_FILE";
export const EDIT_FILE = "EDIT_FILE";
export const TOGGLE_FILE_INPUT = "TOGGLE_FILE_INPUT";
export const CHANGE_CURRENT_FILE_ID = "CHANGE_CURRENT_FILE_ID";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
